name: 'CodeOwnersNotifer'
description: "Github action for notifying codeowners about changes, even if they aren't part of the repo."
branding:
  icon: bell
  color: white
inputs:
  owner:
    description:
      "The owner, for example: \"dotnet\". Assign from `github.repository_owner`."
    required: false
    default: ${{ github.repository_owner }}
  name:
    description:
      "The repository name, for example: \"samples\". Assign from `github.repository`."
    required: false
    default: ${{ github.repository }}
  timeout:
    description:
      "Timeout for Github API requests in milliseconds."
    required: false
    default: '10000'
  fileLimit:
    description:
      "Maximum amount of files to process, PRs with more files will not be processed."
    required: false
    default: '1000'
  token:
    description:
      "Github token used for Github API. Only needed to increase rate limit, may not be provided."
    required: false
    default: ${{ github.token }}
  workspace:
    description:
      "The workspace directory, or repository root directory. Assign from `github.workspace`."
    required: false
    default: "/github/workspace"
  file:
    description:
      "Path to the codeowners file. Relative to the repository root."
    required: false
    default: "/.github/CODEOWNERS"
  pullID:
    description:
      "ID of the PR to process. Assign from `github.event.pull_request.number`."
    required: false
    default: ${{ github.event.pull_request.number }}
  separator:
    description:
      "Separator used if multiple owners are returned. Defaults to space."
    required: false
    default: ' '
  prefix:
    description:
      "Prefix that will be added to owners-formatted output + used for finding existing mentions."
    required: false
    default: ""
  sufix:
    description:
      "Sufix that will be added to owners-formatted output + used for finding existing mentions."
    required: false
    default: ""
  botname:
    description:
      "Name of the bot/user that posts notification comments. If this is specified only owners that haven't been mentioned by this user will be output. Should be 'github-actions[bot]'"
    required: false
outputs:
  owners:
    description:
      'Raw list of owners, seperated with the separator parameter. Use this to determine if owners were found and as input for other actions.'
  owners-formatted:
    description:
      'Owners with sufix and prefix paramter added. Use this output as input for comment posting actions.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-o'
  - ${{ inputs.owner }}
  - '-n'
  - ${{ inputs.name }}
  - '-t'
  - ${{ inputs.timeout }}
  - '-l'
  - ${{ inputs.fileLimit }}
  - '-k'
  - ${{ inputs.token }}
  - '-w'
  - ${{ inputs.workspace }}
  - '-f'
  - ${{ inputs.file }}
  - '-i'
  - ${{ inputs.pullID }}
  - '-d'
  - ${{ inputs.separator }}
  - '-p'
  - ${{ inputs.prefix }}
  - '-s'
  - ${{ inputs.sufix }}
  - '-b'
  - ${{ inputs.botname }}